### PR TITLE
Add failing tests highlighting non conformance with the spec

### PR DESCRIPTION
**Pull request by dunglas**
Hi, and thanks for this library.

The current implementation is not compliant with [the specification](https://html.spec.whatwg.org/multipage/server-sent-events.html). I added a failing test highlighting various problems:

* comments trigger parsing errors
* multiline data isn't handled properly
* spaces between the column and the data aren't ignored

### CODE REVIEW

**Comment by jpopesculian** [comment]
Hi @dunglas! I'm going to be honest, when I wrote this I didn't look exactly at the specification as outlined by WHATWG. I will definitely have a look this week and see if I can add the test coverage necessary.

**Comment by dunglas** [comment]
Hi @jpopesculian, I can open a PR rewriting the parser to implement the algorithm defined in the spec if you want, but it will introduce BC breaks, is that ok for you?

Also, I wonder what you think about https://github.com/lluchs/eventsource. The project looks un maintained (it doesn't support Tokio 1.0) and I prefer the trait approach your libs follow, but the parser of this package is spec-compliant.

**Comment by jpopesculian** [comment]
Hi @dunglas, I think the changes shouldn't be too complex and shouldn't warrant a rewrite. I meant to look at this today, but it's looking to be a busy week with everyone getting back to work. I think the major work will just be adding adequate tests, and I think I'll have something out by the end of the week

**Comment by jpopesculian** [comment]
Hi @dunglas! Haha, I did have to rewrite the parser. The spec is a lot more nuanced than I thought, and the work required for unicode support wasn't worth it, so I thought a rewrite made sense. I haven't written enough tests for it, but the last version also didn't have a lot of tests so I pushed it to the main branch. Take a look!

**Pull request closed without merging**
